/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AmplitudeAnalyticsReportLogDetails: core.serialization.Schema<
    serializers.AmplitudeAnalyticsReportLogDetails.Raw,
    Chkk.AmplitudeAnalyticsReportLogDetails
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace AmplitudeAnalyticsReportLogDetails {
    type Raw = Record<string, unknown>;
}
