/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AmplitudeAnalyticsReport: core.serialization.ObjectSchema<
    serializers.AmplitudeAnalyticsReport.Raw,
    Chkk.AmplitudeAnalyticsReport
> = core.serialization.object({
    logDetails: core.serialization.lazy(async () => (await import("../../..")).AmplitudeAnalyticsReportLogDetails),
});

export declare namespace AmplitudeAnalyticsReport {
    interface Raw {
        logDetails: serializers.AmplitudeAnalyticsReportLogDetails.Raw;
    }
}
