/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AvailabilityRiskComponents: core.serialization.ObjectSchema<
    serializers.AvailabilityRiskComponents.Raw,
    Chkk.AvailabilityRiskComponents
> = core.serialization.object({
    addons: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AvailabilityRiskComponents {
    interface Raw {
        addons?: string[] | null;
    }
}
