/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AvailabilityRiskSeverity: core.serialization.Schema<
    serializers.AvailabilityRiskSeverity.Raw,
    Chkk.AvailabilityRiskSeverity
> = core.serialization.enum_(["critical", "high", "medium", "low"]);

export declare namespace AvailabilityRiskSeverity {
    type Raw = "critical" | "high" | "medium" | "low";
}
