/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AvailabilityRiskStatus: core.serialization.Schema<
    serializers.AvailabilityRiskStatus.Raw,
    Chkk.AvailabilityRiskStatus
> = core.serialization.enum_(["detected", "resolved", "acknowledged", "ignored"]);

export declare namespace AvailabilityRiskStatus {
    type Raw = "detected" | "resolved" | "acknowledged" | "ignored";
}
