/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AvailabilityRisksSummary: core.serialization.ObjectSchema<
    serializers.AvailabilityRisksSummary.Raw,
    Chkk.AvailabilityRisksSummary
> = core.serialization.object({
    data: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).SummaryEntry))
        .optional(),
});

export declare namespace AvailabilityRisksSummary {
    interface Raw {
        data?: serializers.SummaryEntry.Raw[] | null;
    }
}
