/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const QuickStartResponse: core.serialization.ObjectSchema<
    serializers.QuickStartResponse.Raw,
    Chkk.QuickStartResponse
> = core.serialization.object({
    firstCluster: core.serialization.property(
        "first_cluster",
        core.serialization.lazyObject(async () => (await import("../../..")).QuickStartResponseItem)
    ),
    inviteTeamMember: core.serialization.property(
        "invite_team_member",
        core.serialization.lazyObject(async () => (await import("../../..")).QuickStartResponseItem)
    ),
    joinSlack: core.serialization.property(
        "join_slack",
        core.serialization.lazyObject(async () => (await import("../../..")).QuickStartResponseItem)
    ),
});

export declare namespace QuickStartResponse {
    interface Raw {
        first_cluster: serializers.QuickStartResponseItem.Raw;
        invite_team_member: serializers.QuickStartResponseItem.Raw;
        join_slack: serializers.QuickStartResponseItem.Raw;
    }
}
