/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const QuickStartResponseItem: core.serialization.ObjectSchema<
    serializers.QuickStartResponseItem.Raw,
    Chkk.QuickStartResponseItem
> = core.serialization.object({
    status: core.serialization.boolean(),
    title: core.serialization.string(),
    description: core.serialization.string(),
    priority: core.serialization.number(),
    created: core.serialization.number().optional(),
    user: core.serialization.lazyObject(async () => (await import("../../..")).QuickStartResponseItemUser).optional(),
});

export declare namespace QuickStartResponseItem {
    interface Raw {
        status: boolean;
        title: string;
        description: string;
        priority: number;
        created?: number | null;
        user?: serializers.QuickStartResponseItemUser.Raw | null;
    }
}
