/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const Resource: core.serialization.ObjectSchema<serializers.Resource.Raw, Chkk.Resource> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        type: core.serialization.string(),
        metadata: core.serialization.record(
            core.serialization.string(),
            core.serialization.lazy(async () => (await import("../../..")).StringProperty).optional()
        ),
    });

export declare namespace Resource {
    interface Raw {
        id: string;
        name: string;
        type: string;
        metadata: Record<string, serializers.StringProperty.Raw | null | undefined>;
    }
}
