/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const StringArray: core.serialization.Schema<serializers.StringArray.Raw, Chkk.StringArray> =
    core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).StringProperty));

export declare namespace StringArray {
    type Raw = serializers.StringProperty.Raw[];
}
