/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const SubmitFeedbackRequest: core.serialization.ObjectSchema<
    serializers.SubmitFeedbackRequest.Raw,
    Chkk.SubmitFeedbackRequest
> = core.serialization.object({
    title: core.serialization.string(),
    details: core.serialization.string(),
    userEmail: core.serialization.property("user_email", core.serialization.string()),
});

export declare namespace SubmitFeedbackRequest {
    interface Raw {
        title: string;
        details: string;
        user_email: string;
    }
}
