/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const CreateIntegrationRequest: core.serialization.ObjectSchema<
    serializers.CreateIntegrationRequest.Raw,
    Chkk.CreateIntegrationRequest
> = core.serialization.object({
    integrationName: core.serialization.property("integration_name", core.serialization.string()),
    integrationType: core.serialization.property(
        "integration_type",
        core.serialization.lazy(async () => (await import("../../..")).IntegrationType)
    ),
    status: core.serialization.lazy(async () => (await import("../../..")).IntegrationStatus),
    slackConfiguration: core.serialization.property(
        "slack_configuration",
        core.serialization.lazyObject(async () => (await import("../../..")).IntegrationSlackConfiguration).optional()
    ),
    jiraConfiguration: core.serialization.property(
        "jira_configuration",
        core.serialization.lazyObject(async () => (await import("../../..")).IntegrationJiraConfiguration).optional()
    ),
});

export declare namespace CreateIntegrationRequest {
    interface Raw {
        integration_name: string;
        integration_type: serializers.IntegrationType.Raw;
        status: serializers.IntegrationStatus.Raw;
        slack_configuration?: serializers.IntegrationSlackConfiguration.Raw | null;
        jira_configuration?: serializers.IntegrationJiraConfiguration.Raw | null;
    }
}
