/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const CreateTicketRequestAffectedResource: core.serialization.ObjectSchema<
    serializers.CreateTicketRequestAffectedResource.Raw,
    Chkk.CreateTicketRequestAffectedResource
> = core.serialization.object({
    name: core.serialization.string(),
    kind: core.serialization.string(),
    namespace: core.serialization.string(),
});

export declare namespace CreateTicketRequestAffectedResource {
    interface Raw {
        name: string;
        kind: string;
        namespace: string;
    }
}
