/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationSlackAppConfigurationBot: core.serialization.ObjectSchema<
    serializers.IntegrationSlackAppConfigurationBot.Raw,
    Chkk.IntegrationSlackAppConfigurationBot
> = core.serialization.object({
    token: core.serialization.string(),
    refreshToken: core.serialization.string().optional(),
    expiresAt: core.serialization.number().optional(),
    id: core.serialization.string(),
    userId: core.serialization.string(),
});

export declare namespace IntegrationSlackAppConfigurationBot {
    interface Raw {
        token: string;
        refreshToken?: string | null;
        expiresAt?: number | null;
        id: string;
        userId: string;
    }
}
