/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationSlackConfiguration: core.serialization.ObjectSchema<
    serializers.IntegrationSlackConfiguration.Raw,
    Chkk.IntegrationSlackConfiguration
> = core.serialization.object({
    channels: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).IntegrationSlackChannel)
    ),
});

export declare namespace IntegrationSlackConfiguration {
    interface Raw {
        channels: serializers.IntegrationSlackChannel.Raw[];
    }
}
