/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationSlackAppConfigurationUser: core.serialization.ObjectSchema<
    serializers.IntegrationSlackAppConfigurationUser.Raw,
    Chkk.IntegrationSlackAppConfigurationUser
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace IntegrationSlackAppConfigurationUser {
    interface Raw {
        id: string;
    }
}
