/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationType: core.serialization.Schema<serializers.IntegrationType.Raw, Chkk.IntegrationType> =
    core.serialization.string();

export declare namespace IntegrationType {
    type Raw = string;
}
