/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationStatus: core.serialization.Schema<serializers.IntegrationStatus.Raw, Chkk.IntegrationStatus> =
    core.serialization.string();

export declare namespace IntegrationStatus {
    type Raw = string;
}
