/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IntegrationSlackChannel: core.serialization.ObjectSchema<
    serializers.IntegrationSlackChannel.Raw,
    Chkk.IntegrationSlackChannel
> = core.serialization.object({
    name: core.serialization.string().optional(),
    severity: core.serialization.string().optional(),
    slackApiUrl: core.serialization.property("slack_api_url", core.serialization.string()),
});

export declare namespace IntegrationSlackChannel {
    interface Raw {
        name?: string | null;
        severity?: string | null;
        slack_api_url: string;
    }
}
