/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ListIntegrationsResponse: core.serialization.ObjectSchema<
    serializers.ListIntegrationsResponse.Raw,
    Chkk.ListIntegrationsResponse
> = core.serialization.object({
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Integration)),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
});

export declare namespace ListIntegrationsResponse {
    interface Raw {
        data: serializers.Integration.Raw[];
        has_more: boolean;
    }
}
