/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const UpdateIntegrationRequest: core.serialization.ObjectSchema<
    serializers.UpdateIntegrationRequest.Raw,
    Chkk.UpdateIntegrationRequest
> = core.serialization.object({
    integrationName: core.serialization.property("integration_name", core.serialization.string()),
    status: core.serialization.lazy(async () => (await import("../../..")).IntegrationStatus).optional(),
});

export declare namespace UpdateIntegrationRequest {
    interface Raw {
        integration_name: string;
        status?: serializers.IntegrationStatus.Raw | null;
    }
}
