/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * request from the collector to trigger the processing of a new scan
 */
export interface CreateClusterScanRequestBody {
    clusterId: string;
    userToken: string;
    rescanStatus: string;
}
