/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ???
 */
export interface CreateScanResponse {
    /** The ID of the created Scan object */
    id: string;
    /** The last status of the create Scan object */
    status: string;
    /** The timestamp of the creation of the new Scan object */
    created: number;
}
