/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const CreateScanRequest: core.serialization.ObjectSchema<
    serializers.CreateScanRequest.Raw,
    Chkk.CreateScanRequest
> = core.serialization.object({
    clusterId: core.serialization.property("cluster_id", core.serialization.string()),
});

export declare namespace CreateScanRequest {
    interface Raw {
        cluster_id: string;
    }
}
