/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const RescanClusterRequestBody: core.serialization.ObjectSchema<
    serializers.RescanClusterRequestBody.Raw,
    Chkk.RescanClusterRequestBody
> = core.serialization.object({
    rescanStatus: core.serialization.property(
        "rescan_status",
        core.serialization.lazy(async () => (await import("../../..")).ClusterRescan)
    ),
});

export declare namespace RescanClusterRequestBody {
    interface Raw {
        rescan_status: serializers.ClusterRescan.Raw;
    }
}
