/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A component of the resource which submitted the notification.
 */
export interface AgentComponent {
    /** The name of the component. */
    name: string;
    /** The image mounted on the component. */
    image: string;
    /** Type of image the component uses. E.g OCI,AMI,etc */
    imageType?: string;
    state: Chkk.ResourceStatus;
    /** The reason for the state of the component. */
    reason?: string;
}
