/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the resource.
 */
export type ResourceStatus = "Waiting" | "Terminated" | "Running" | "Unknown";

export const ResourceStatus = {
    Waiting: "Waiting",
    Terminated: "Terminated",
    Running: "Running",
    Unknown: "Unknown",
} as const;
