/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

export interface SubmitAgentStatusNotificationRequestBody {
    /** The ID of the resource that the notification is about. */
    resourceId: string;
    /** List of components reported as part of the notification. */
    components: Chkk.AgentComponent[];
}
