/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AccessToken: core.serialization.ObjectSchema<serializers.AccessToken.Raw, Chkk.AccessToken> =
    core.serialization.object({
        accessToken: core.serialization.property("access_token", core.serialization.string()),
        userId: core.serialization.property("user_id", core.serialization.string().optional()),
        orgId: core.serialization.property("org_id", core.serialization.string().optional()),
        accountId: core.serialization.property("account_id", core.serialization.string().optional()),
        created: core.serialization.number(),
    });

export declare namespace AccessToken {
    interface Raw {
        access_token: string;
        user_id?: string | null;
        org_id?: string | null;
        account_id?: string | null;
        created: number;
    }
}
