/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AccountAccessToken: core.serialization.Schema<
    serializers.AccountAccessToken.Raw,
    Chkk.AccountAccessToken
> = core.serialization.record(
    core.serialization.string(),
    core.serialization.lazy(async () => (await import("../../..")).InlineTypeString).optional()
);

export declare namespace AccountAccessToken {
    type Raw = Record<string, serializers.InlineTypeString.Raw | null | undefined>;
}
