/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const GetIngestionTokenResponse: core.serialization.ObjectSchema<
    serializers.GetIngestionTokenResponse.Raw,
    Chkk.GetIngestionTokenResponse
> = core.serialization.object({
    token: core.serialization.string(),
    created: core.serialization.number(),
    expiration: core.serialization.number(),
    revoked: core.serialization.number(),
});

export declare namespace GetIngestionTokenResponse {
    interface Raw {
        token: string;
        created: number;
        expiration: number;
        revoked: number;
    }
}
