/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const GetUsersResponse: core.serialization.ObjectSchema<
    serializers.GetUsersResponse.Raw,
    Chkk.GetUsersResponse
> = core.serialization.object({
    accountId: core.serialization.property("account_id", core.serialization.string().optional()),
    email: core.serialization.string(),
    name: core.serialization.string(),
});

export declare namespace GetUsersResponse {
    interface Raw {
        account_id?: string | null;
        email: string;
        name: string;
    }
}
