/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ListTeamInvitationsResponse: core.serialization.ObjectSchema<
    serializers.ListTeamInvitationsResponse.Raw,
    Chkk.ListTeamInvitationsResponse
> = core.serialization.object({
    continuationToken: core.serialization.property("continuation_token", core.serialization.string()),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).TeamInvitation)),
});

export declare namespace ListTeamInvitationsResponse {
    interface Raw {
        continuation_token: string;
        data: serializers.TeamInvitation.Raw[];
    }
}
