/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ListAccessTokensResponse: core.serialization.ObjectSchema<
    serializers.ListAccessTokensResponse.Raw,
    Chkk.ListAccessTokensResponse
> = core.serialization.object({
    continuationToken: core.serialization.property("continuation_token", core.serialization.string()),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).AccessToken)),
});

export declare namespace ListAccessTokensResponse {
    interface Raw {
        continuation_token: string;
        data: serializers.AccessToken.Raw[];
    }
}
