/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const OrganizationStatus: core.serialization.Schema<
    serializers.OrganizationStatus.Raw,
    Chkk.OrganizationStatus
> = core.serialization.enum_(["ACTIVE", "INACTIVE", "DEACTIVATED"]);

export declare namespace OrganizationStatus {
    type Raw = "ACTIVE" | "INACTIVE" | "DEACTIVATED";
}
