/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const TeamInvitation: core.serialization.ObjectSchema<serializers.TeamInvitation.Raw, Chkk.TeamInvitation> =
    core.serialization.object({
        id: core.serialization.string(),
        email: core.serialization.string(),
        orgId: core.serialization.property("org_id", core.serialization.string()),
        inviteUrl: core.serialization.property("invite_url", core.serialization.string()),
        inviteKey: core.serialization.property("invite_key", core.serialization.string()),
        inviter: core.serialization.string(),
        created: core.serialization.number(),
        expiry: core.serialization.number().optional(),
        status: core.serialization.lazy(async () => (await import("../../..")).TeamInvitationStatus),
    });

export declare namespace TeamInvitation {
    interface Raw {
        id: string;
        email: string;
        org_id: string;
        invite_url: string;
        invite_key: string;
        inviter: string;
        created: number;
        expiry?: number | null;
        status: serializers.TeamInvitationStatus.Raw;
    }
}
