/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const Team: core.serialization.ObjectSchema<serializers.Team.Raw, Chkk.Team> = core.serialization.object({
    id: core.serialization.string(),
    accountId: core.serialization.property("account_id", core.serialization.string()),
    slug: core.serialization.string(),
    name: core.serialization.string(),
    created: core.serialization.number(),
    updated: core.serialization.number().optional(),
    members: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../..")).TeamMember))
        .optional(),
});

export declare namespace Team {
    interface Raw {
        id: string;
        account_id: string;
        slug: string;
        name: string;
        created: number;
        updated?: number | null;
        members?: serializers.TeamMember.Raw[] | null;
    }
}
