/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const TeamMember: core.serialization.ObjectSchema<serializers.TeamMember.Raw, Chkk.TeamMember> =
    core.serialization.object({
        userId: core.serialization.property("user_id", core.serialization.string()),
        userEmail: core.serialization.property("user_email", core.serialization.string()),
        userName: core.serialization.property("user_name", core.serialization.string()),
        userPicture: core.serialization.property("user_picture", core.serialization.string().optional()),
        dateAdded: core.serialization.property("date_added", core.serialization.number()),
        status: core.serialization.lazy(async () => (await import("../../..")).MembershipStatus),
    });

export declare namespace TeamMember {
    interface Raw {
        user_id: string;
        user_email: string;
        user_name: string;
        user_picture?: string | null;
        date_added: number;
        status: serializers.MembershipStatus.Raw;
    }
}
