/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetAvailabilityRisksSummaryRequest {
    /**
     * summary operation will apply filter and group_by clauses, and then count distinct values in the field specified for count parameter. Possible values are affected_resources, availability_risks
     */
    count: string;
}
