/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetAvailabilityRiskAffectedResourceRequest {
    /**
     * The filter can include one or multiple clauses separated by commas, e.g., type:cluster, cluster_id:k8scl_1234 etc.
     */
    filter?: string | string[];
    /**
     * The number of entries returned in a single call.
     */
    pageSize?: number;
    /**
     * The continuation token recieved in a prior call, for this call to return the next set of results
     */
    continuationToken?: string;
}
