/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListAccountTeamsRequest {
    /**
     * The number of entries returned in a single call.
     */
    pageSize?: number;
    /**
     * The continuation token recieved in a prior call, for this call to return the next set of results
     */
    continuationToken?: string;
}
