/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ClusterRequestTypeString: core.serialization.Schema<
    serializers.ClusterRequestTypeString.Raw,
    Chkk.ClusterRequestTypeString
> = core.serialization.string();

export declare namespace ClusterRequestTypeString {
    type Raw = string;
}
