/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const DeactivateClusterRequestBody: core.serialization.ObjectSchema<
    serializers.DeactivateClusterRequestBody.Raw,
    Chkk.DeactivateClusterRequestBody
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../..")).ClusterStatus),
});

export declare namespace DeactivateClusterRequestBody {
    interface Raw {
        status: serializers.ClusterStatus.Raw;
    }
}
