/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const UpdateClusterRequest: core.serialization.ObjectSchema<
    serializers.UpdateClusterRequest.Raw,
    Chkk.UpdateClusterRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    region: core.serialization.string().optional(),
    production: core.serialization.boolean().optional(),
    version: core.serialization.string().optional(),
    nodeCount: core.serialization.property("node_count", core.serialization.number().optional()),
    managedNgCount: core.serialization.property("managed_ng_count", core.serialization.number().optional()),
    selfManagedNgCount: core.serialization.property("self_managed_ng_count", core.serialization.number().optional()),
    containerRuntimes: core.serialization.property(
        "container_runtimes",
        core.serialization.list(core.serialization.string()).optional()
    ),
    labels: core.serialization
        .record(
            core.serialization.string(),
            core.serialization.lazy(async () => (await import("../../..")).InlineTypeString).optional()
        )
        .optional(),
    cloudProvider: core.serialization.property(
        "cloud_provider",
        core.serialization.lazy(async () => (await import("../../..")).KubernetesProvider).optional()
    ),
    chkkMetadata: core.serialization.property(
        "chkk_metadata",
        core.serialization.lazyObject(async () => (await import("../../..")).ChkkAgent).optional()
    ),
});

export declare namespace UpdateClusterRequest {
    interface Raw {
        name?: string | null;
        region?: string | null;
        production?: boolean | null;
        version?: string | null;
        node_count?: number | null;
        managed_ng_count?: number | null;
        self_managed_ng_count?: number | null;
        container_runtimes?: string[] | null;
        labels?: Record<string, serializers.InlineTypeString.Raw | null | undefined> | null;
        cloud_provider?: serializers.KubernetesProvider.Raw | null;
        chkk_metadata?: serializers.ChkkAgent.Raw | null;
    }
}
