/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AcknowledgeLarRequestBody {
    /** Whether to acknowledge or unacknowledge the LAR */
    acknowledge: boolean;
}
