/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ???
 */
export interface LarsOverviewResponseItemLar {
    signatureId: string;
    severity: string;
    clusterId: string;
    title: string;
    resolved: boolean;
    acknowledged: boolean;
    ignored: boolean;
}
