/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface LarStatus {
    /** The ID of cluster that the LAR exists in */
    clusterId: string;
    /** The ID of the LAR */
    larId: string;
    /** The JIRA ticket associated with the LAR */
    jiraTicket?: string;
    /** The ID of the issue associated with the LAR */
    issueId?: string;
    /** Whether the LAR is ignored/unignored */
    ignore: boolean;
    /** Whether the LAR is acknowledged/unacknowledged */
    acknowledge: boolean;
    /** The severity of the LAR */
    severity?: string;
    /** The ID of the user that updated the LAR's status */
    userId?: string;
    /** The time the LAR was created */
    created?: number;
    /** The time the LAR was last updated */
    updated?: number;
}
