/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Chkk } from "@fern-api/chkk";
import urlJoin from "url-join";
import * as serializers from "../../../../serialization";
import * as errors from "../../../../errors";

export declare namespace Subscription {
    interface Options {
        environment: environments.ChkkEnvironment | string;
        apiKey?: core.Supplier<string>;
    }
}

export class Subscription {
    constructor(private readonly options: Subscription.Options) {}

    /**
     * Retrieve all the subscriptions associated with a Chkk account
     */
    public async list(accountSlug: string): Promise<Chkk.ListSubscriptionsResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, `/accounts/${accountSlug}/subscriptions`),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
        });
        if (_response.ok) {
            return await serializers.ListSubscriptionsResponse.parseOrThrow(
                _response.body as serializers.ListSubscriptionsResponse.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChkkError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChkkError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ChkkTimeoutError();
            case "unknown":
                throw new errors.ChkkError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Add a new subscription to the account
     */
    public async create(
        accountSlug: string,
        request: Chkk.CreateSubscriptionRequest
    ): Promise<Chkk.CreateSubscriptionResponse> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, `/accounts/${accountSlug}/subscriptions`),
            method: "POST",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.CreateSubscriptionRequest.jsonOrThrow(request),
        });
        if (_response.ok) {
            return await serializers.CreateSubscriptionResponse.parseOrThrow(
                _response.body as serializers.CreateSubscriptionResponse.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChkkError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChkkError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ChkkTimeoutError();
            case "unknown":
                throw new errors.ChkkError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Retrieve the details of a specific subscription
     */
    public async get(accountSlug: string, subscriptionId: string): Promise<Chkk.ResolvedSubscription> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, `/accounts/${accountSlug}/subscriptions/${subscriptionId}`),
            method: "GET",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
        });
        if (_response.ok) {
            return await serializers.ResolvedSubscription.parseOrThrow(
                _response.body as serializers.ResolvedSubscription.Raw,
                { allowUnknownKeys: true }
            );
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChkkError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChkkError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ChkkTimeoutError();
            case "unknown":
                throw new errors.ChkkError({
                    message: _response.error.errorMessage,
                });
        }
    }

    /**
     * Update the properties of a specific subscription
     */
    public async update(
        accountSlug: string,
        subscriptionId: string,
        request: Chkk.UpdateSubscriptionRequestBody
    ): Promise<void> {
        const _response = await core.fetcher({
            url: urlJoin(this.options.environment, `/accounts/${accountSlug}/subscriptions/${subscriptionId}`),
            method: "PUT",
            headers: {
                Authorization: await core.Supplier.get(this.options.apiKey),
            },
            body: await serializers.UpdateSubscriptionRequestBody.jsonOrThrow(request),
        });
        if (_response.ok) {
            return;
        }

        if (_response.error.reason === "status-code") {
            throw new errors.ChkkError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.ChkkError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                });
            case "timeout":
                throw new errors.ChkkTimeoutError();
            case "unknown":
                throw new errors.ChkkError({
                    message: _response.error.errorMessage,
                });
        }
    }
}
