/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An access token as used by the Chkk API for authentication
 */
export interface AccessToken {
    /** The actual token to be used in Authorization header */
    accessToken: string;
    /** The ID of the user represented by the access token */
    userId?: string;
    /** The ID of the organization represented by the access token */
    orgId?: string;
    /** The ID of the account represented by the access token */
    accountId?: string;
    /** Time at which the access token was created. Measured in seconds since the Unix epoch */
    created: number;
}
