/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A mapping from account slug (in the org) to the access token
 */
export type AccountAccessToken = Record<string, Chkk.InlineTypeString | undefined>;
