/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The body of a request to add a user to a Chkk Team
 */
export interface AddTeamMemberRequest {
    /** The email address of the user to add to the Chkk Team */
    memberEmail: string;
}
