/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A JWT as used by the Chkk API for authentication
 */
export interface GetIngestionTokenResponse {
    /** The actual token to be used in Authorization header */
    token: string;
    /** Time at which the jwt token was created. Measured in seconds since the Unix epoch */
    created: number;
    /** Time at which the jwt token will expire. Measured in seconds since the Unix epoch */
    expiration: number;
    /** Time at which the jwt token was revoked. Measured in seconds since the Unix epoch */
    revoked: number;
}
