/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A list of access tokens the caller has access to
 */
export interface ListAccessTokensResponse {
    /** a token to get the next page of results, or an empty string if no further results are available */
    continuationToken: string;
    data: Chkk.AccessToken[];
}
