/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * Response for listing invitations in a team
 */
export interface ListTeamInvitationsResponse {
    /** a token to get the next page of results, or an empty string if no further results are available */
    continuationToken: string;
    data: Chkk.TeamInvitation[];
}
