/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * Response to a login call, detailing the organizations available to a user
 */
export interface LoginResponse {
    /** a token to get the next page of results, or an empty string if no further results are available */
    continuationToken: string;
    orgs: Chkk.Organization[];
    /** For each org ID that you have access to, this contains the access tokens needed to access it */
    accessTokens?: Record<string, Chkk.AccountAccessToken | undefined>;
}
