/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of a user's membership in a team. A user can be INVITED (before they accept the invitation) or ACTIVE (they are a member of the team)
 */
export type MembershipStatus = "ACTIVE" | "INACTIVE" | "DEACTIVATED" | "INVITED";

export const MembershipStatus = {
    Active: "ACTIVE",
    Inactive: "INACTIVE",
    Deactivated: "DEACTIVATED",
    Invited: "INVITED",
} as const;
