/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A Chkk Organization, which owns a set of accounts. In most cases a Chkk Organization will map 1:1 to a customer, with different departments and use cases being modeled as different accounts.
 */
export interface Organization {
    /** Organization identifier */
    id: string;
    /** A human-readable, unique identifier for the Organization */
    slug: string;
    /** Display name of the Organization */
    name: string;
    /** Time at which the Organization was created. Measured in seconds since the Unix epoch */
    created: number;
    /** Time at which the Organization was updated. Measured in seconds since the Unix epoch */
    updated?: number;
    status: Chkk.OrganizationStatus;
    /** Company / Organization physical address */
    address?: string;
    /** URL of the Organization logo */
    logoUrl?: string;
    /** Link to the Organization website */
    website?: string;
}
