/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * Details of an invitation for a user to join a Chkk Team
 */
export interface TeamInvitation {
    /** Invitation identifier */
    id: string;
    /** The user's email */
    email: string;
    /** Organization ID */
    orgId: string;
    /** Invite URL */
    inviteUrl: string;
    /** Invite key */
    inviteKey: string;
    /** The person inviting */
    inviter: string;
    /** Time at which the invite was created. Measured in seconds since the Unix epoch */
    created: number;
    /** Time at which the invite will expire. Measured in seconds since the Unix epoch */
    expiry?: number;
    status: Chkk.TeamInvitationStatus;
}
