/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the invite
 */
export type TeamInvitationStatus = "ACCEPTED" | "PENDING";

export const TeamInvitationStatus = {
    Accepted: "ACCEPTED",
    Pending: "PENDING",
} as const;
