/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Update the details of a Chkk Organization
 */
export interface UpdateOrganizationRequest {
    /** Display name of the Organization */
    name?: string;
    /** URL of the Organization logo */
    logoUrl?: string;
    /** Company / Organization physical address */
    address?: string;
    /** Link to the Organization website */
    website?: string;
}
