/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const CreateSubscriptionRequestBody: core.serialization.ObjectSchema<
    serializers.CreateSubscriptionRequestBody.Raw,
    Chkk.CreateSubscriptionRequestBody
> = core.serialization.object({
    subscriptionType: core.serialization.property(
        "subscription_type",
        core.serialization.lazy(async () => (await import("../../..")).SubscriptionType)
    ),
    awsRegistrationToken: core.serialization.property("aws_registration_token", core.serialization.string().optional()),
});

export declare namespace CreateSubscriptionRequestBody {
    interface Raw {
        subscription_type: serializers.SubscriptionType.Raw;
        aws_registration_token?: string | null;
    }
}
