/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const CreateSubscriptionResponse: core.serialization.ObjectSchema<
    serializers.CreateSubscriptionResponse.Raw,
    Chkk.CreateSubscriptionResponse
> = core.serialization.object({
    accountId: core.serialization.property("account_id", core.serialization.string()),
    subscriptionId: core.serialization.property("subscription_id", core.serialization.string()),
});

export declare namespace CreateSubscriptionResponse {
    interface Raw {
        account_id: string;
        subscription_id: string;
    }
}
