/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ResolvedEntitlement: core.serialization.ObjectSchema<
    serializers.ResolvedEntitlement.Raw,
    Chkk.ResolvedEntitlement
> = core.serialization.object({
    nodeCount: core.serialization.property("node_count", core.serialization.number()),
    smallClusters: core.serialization.property("small_clusters", core.serialization.number().optional()),
    mediumClusters: core.serialization.property("medium_clusters", core.serialization.number().optional()),
    largeClusters: core.serialization.property("large_clusters", core.serialization.number().optional()),
});

export declare namespace ResolvedEntitlement {
    interface Raw {
        node_count: number;
        small_clusters?: number | null;
        medium_clusters?: number | null;
        large_clusters?: number | null;
    }
}
