/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const SubscriptionPlan: core.serialization.Schema<serializers.SubscriptionPlan.Raw, Chkk.SubscriptionPlan> =
    core.serialization.enum_(["Community", "Business", "Enterprise"]);

export declare namespace SubscriptionPlan {
    type Raw = "Community" | "Business" | "Enterprise";
}
