/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const SubscriptionType: core.serialization.Schema<serializers.SubscriptionType.Raw, Chkk.SubscriptionType> =
    core.serialization.enum_(["CommunityEdition", "AWSMarketplace"]);

export declare namespace SubscriptionType {
    type Raw = "CommunityEdition" | "AWSMarketplace";
}
