/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const UpdateSubscriptionRequestBody: core.serialization.ObjectSchema<
    serializers.UpdateSubscriptionRequestBody.Raw,
    Chkk.UpdateSubscriptionRequestBody
> = core.serialization.object({});

export declare namespace UpdateSubscriptionRequestBody {
    interface Raw {}
}
