/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Amplitude event as defined at https://github.com/amplitude/analytics-go/blob/main/amplitude/types/event.go#L3
 */
export type AmplitudeAnalyticsReportLogDetails = Record<string, unknown>;
