/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * different states of an Availability Risk
 */
export type AvailabilityRiskStatus = "detected" | "resolved" | "acknowledged" | "ignored";

export const AvailabilityRiskStatus = {
    Detected: "detected",
    Resolved: "resolved",
    Acknowledged: "acknowledged",
    Ignored: "ignored",
} as const;
