/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * An Availability Risk is an instance of Availability Risk Signature which has failed in a cluster
 */
export interface AvailabilityRisk {
    id: string;
    title: string;
    category?: string[];
    status?: Chkk.AvailabilityRiskStatus;
    needAttention?: boolean;
    severity: Chkk.AvailabilityRiskSeverity;
    availabilityImpact: string;
    labels: Record<string, Chkk.StringArray | undefined>;
    components: Chkk.AvailabilityRiskComponents;
    affectedResourceSummary: Chkk.AvailabilityRiskAffectedResourceSummary;
}
