/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * Counts of Availability Risks or affected resources, given a group by clause and filters
 */
export interface AvailabilityRisksSummary {
    data?: Chkk.SummaryEntry[];
}
