/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * severities of an Availability Risk
 */
export type AvailabilityRiskSeverity = "critical" | "high" | "medium" | "low";

export const AvailabilityRiskSeverity = {
    Critical: "critical",
    High: "high",
    Medium: "medium",
    Low: "low",
} as const;
