/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A response to a request to list the Resources in a given Chkk Account
 */
export interface ListAffectedResourcesResponse {
    availabilityRisk?: Chkk.AvailabilityRisk;
    /** List of Resource items */
    data: Chkk.Resource[];
    /** a token to get the next page of results, or an empty string if no further results are available */
    continuationToken: string;
}
