/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface QuickStartResponse {
    firstCluster: Chkk.QuickStartResponseItem;
    inviteTeamMember: Chkk.QuickStartResponseItem;
    joinSlack: Chkk.QuickStartResponseItem;
}
