/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface QuickStartResponseItem {
    status: boolean;
    title: string;
    description: string;
    priority: number;
    created?: number;
    user?: Chkk.QuickStartResponseItemUser;
}
