/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * A resource is an object of any kind in the k8s cluster, e.g. cluster, namespace, addons etc.
 */
export interface Resource {
    /** resource id, e.g. k8scl_1234, ngsamespace_id, addon_id etc. */
    id: string;
    /** resource's name. */
    name: string;
    /** e.g. cluster, namespace, addon */
    type: string;
    /** resource's metadata, e.g., label, version, and region etc. */
    metadata: Record<string, Chkk.StringProperty | undefined>;
}
