/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

export interface CreateSubscriptionRequestBody {
    subscriptionType: Chkk.SubscriptionType;
    /** The registration token as vended by the AWS Marketplace */
    awsRegistrationToken?: string;
}
