/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * Details of a subscription including potentially external information (e.g. from cloud marketplaces)
 */
export interface ResolvedSubscription {
    /** The Chkk account ID owning the subscription */
    accountId: string;
    /** The ID of the subscription itself */
    subscriptionId: string;
    /** Human readable description of the subscription, e.g. "Chkk (Business Edition)" */
    name: string;
    type: Chkk.SubscriptionType;
    plan: Chkk.SubscriptionPlan;
    entitlement: Chkk.ResolvedEntitlement;
}
