/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Description of a resource entitlement. This follows the Chkk pricing structure - please refer there for details of the different dimensions
 */
export interface ResolvedEntitlement {
    /** Number of nodes across the infrastrcuture in this entitlement */
    nodeCount: number;
    /** Number of small clusters included in this entitlement */
    smallClusters?: number;
    /** Number of medium clusters included in this entitlement */
    mediumClusters?: number;
    /** Number of large clusters included in this entitlement */
    largeClusters?: number;
}
