/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The kind of plan a subscription follows
 */
export type SubscriptionPlan = "Community" | "Business" | "Enterprise";

export const SubscriptionPlan = {
    Community: "Community",
    Business: "Business",
    Enterprise: "Enterprise",
} as const;
