/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of subscription aka how it is managed and charged
 */
export type SubscriptionType = "CommunityEdition" | "AWSMarketplace";

export const SubscriptionType = {
    CommunityEdition: "CommunityEdition",
    AwsMarketplace: "AWSMarketplace",
} as const;
