/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AcknowledgeLarRequest: core.serialization.ObjectSchema<
    serializers.AcknowledgeLarRequest.Raw,
    Chkk.AcknowledgeLarRequest
> = core.serialization.object({
    acknowledge: core.serialization.boolean(),
});

export declare namespace AcknowledgeLarRequest {
    interface Raw {
        acknowledge: boolean;
    }
}
