/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const AcknowledgeLarRequestBody: core.serialization.ObjectSchema<
    serializers.AcknowledgeLarRequestBody.Raw,
    Chkk.AcknowledgeLarRequestBody
> = core.serialization.object({
    acknowledge: core.serialization.boolean(),
});

export declare namespace AcknowledgeLarRequestBody {
    interface Raw {
        acknowledge: boolean;
    }
}
