/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IgnoreLarRequestBody: core.serialization.ObjectSchema<
    serializers.IgnoreLarRequestBody.Raw,
    Chkk.IgnoreLarRequestBody
> = core.serialization.object({
    ignore: core.serialization.boolean(),
});

export declare namespace IgnoreLarRequestBody {
    interface Raw {
        ignore: boolean;
    }
}
