/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const IgnoreLarRequest: core.serialization.ObjectSchema<
    serializers.IgnoreLarRequest.Raw,
    Chkk.IgnoreLarRequest
> = core.serialization.object({
    ignore: core.serialization.boolean(),
});

export declare namespace IgnoreLarRequest {
    interface Raw {
        ignore: boolean;
    }
}
