/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const LarsOverviewResponseItem: core.serialization.ObjectSchema<
    serializers.LarsOverviewResponseItem.Raw,
    Chkk.LarsOverviewResponseItem
> = core.serialization.object({
    period: core.serialization.string(),
    lars: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).LarsOverviewResponseItemLar)
    ),
});

export declare namespace LarsOverviewResponseItem {
    interface Raw {
        period: string;
        lars: serializers.LarsOverviewResponseItemLar.Raw[];
    }
}
