/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const LarsOverviewResponseItemLar: core.serialization.ObjectSchema<
    serializers.LarsOverviewResponseItemLar.Raw,
    Chkk.LarsOverviewResponseItemLar
> = core.serialization.object({
    signatureId: core.serialization.property("signature_id", core.serialization.string()),
    severity: core.serialization.string(),
    clusterId: core.serialization.property("cluster_id", core.serialization.string()),
    title: core.serialization.string(),
    resolved: core.serialization.boolean(),
    acknowledged: core.serialization.boolean(),
    ignored: core.serialization.boolean(),
});

export declare namespace LarsOverviewResponseItemLar {
    interface Raw {
        signature_id: string;
        severity: string;
        cluster_id: string;
        title: string;
        resolved: boolean;
        acknowledged: boolean;
        ignored: boolean;
    }
}
