/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const LarStatus: core.serialization.ObjectSchema<serializers.LarStatus.Raw, Chkk.LarStatus> =
    core.serialization.object({
        clusterId: core.serialization.property("cluster_id", core.serialization.string()),
        larId: core.serialization.property("lar_id", core.serialization.string()),
        jiraTicket: core.serialization.property("jira_ticket", core.serialization.string().optional()),
        issueId: core.serialization.property("issue_id", core.serialization.string().optional()),
        ignore: core.serialization.boolean(),
        acknowledge: core.serialization.boolean(),
        severity: core.serialization.string().optional(),
        userId: core.serialization.property("user_id", core.serialization.string().optional()),
        created: core.serialization.number().optional(),
        updated: core.serialization.number().optional(),
    });

export declare namespace LarStatus {
    interface Raw {
        cluster_id: string;
        lar_id: string;
        jira_ticket?: string | null;
        issue_id?: string | null;
        ignore: boolean;
        acknowledge: boolean;
        severity?: string | null;
        user_id?: string | null;
        created?: number | null;
        updated?: number | null;
    }
}
