/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const LarsOverviewResponse: core.serialization.ObjectSchema<
    serializers.LarsOverviewResponse.Raw,
    Chkk.LarsOverviewResponse
> = core.serialization.object({
    data: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).LarsOverviewResponseItem)
    ),
});

export declare namespace LarsOverviewResponse {
    interface Raw {
        data: serializers.LarsOverviewResponseItem.Raw[];
    }
}
