/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetResourceRequest {
    /**
     * the type of integration that the resource is retrieved for
     */
    integrationType: string;
    /**
     * the name of the resource to be retrieved
     */
    resourceName: string;
}
