/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface ChkkAgent {
    version: string;
    gitCommit: string;
    buildDate: string;
    config: Record<string, Chkk.InlineTypeString | undefined>;
    namespace: string;
}
