/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface ClusterScan {
    id: string;
    clusterId: string;
    status: Chkk.ClusterScanStatus;
    signatures?: Chkk.ClusterScannedSignature[];
    signatureCount: number;
    lars?: Chkk.ClusterDetectedLar[];
    larCount: number;
    created: number;
    updated?: number;
}
