/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface ClusterScannedSignature {
    signatureId: string;
    severity: Chkk.Severity;
    availabilityImpact: string;
    title: string;
    url: string;
    detected: boolean;
    labels: Chkk.SignatureLabel[];
}
