/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface Cluster {
    id: string;
    name?: string;
    internalK8SRef: string;
    accountId: string;
    region: string;
    status: Chkk.ClusterStatus;
    /** whether this cluster should be considered to be part of production or not */
    production?: boolean;
    version: string;
    nodeCount: number;
    managedNgCount: number;
    selfManagedNgCount: number;
    containerRuntimes: string[];
    labels: Record<string, Chkk.InlineTypeString | undefined>;
    cloudProvider: Chkk.KubernetesProvider;
    chkkMetadata: Chkk.ChkkAgent;
    created: number;
    updated?: number;
    rescan: Chkk.ClusterRescan;
    eolDate: number;
    k8SReleaseDate: number;
    k8SProviderRelease: number;
}
