/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ???
 */
export type KubernetesProvider = "EKS" | "KinD" | "GKE" | "AKS" | "Minikube" | "local";

export const KubernetesProvider = {
    Eks: "EKS",
    KinD: "KinD",
    Gke: "GKE",
    Aks: "AKS",
    Minikube: "Minikube",
    Local: "local",
} as const;
