/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface ListClusterScansResponse {
    hasMore: boolean;
    data: Chkk.ClusterScan[];
}
