/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ???
 */
export type Severity = "Critical" | "High" | "Medium" | "Low";

export const Severity = {
    Critical: "Critical",
    High: "High",
    Medium: "Medium",
    Low: "Low",
} as const;
