/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const ChkkEnvironment = {
    /**
     * Prod
     */
    Production: "https://api.chkk.dev/v1",
    /**
     * Prod AWS US-West-2
     */
    ProductionAwsUsWest2: "https://api.us-west-2.aws.chkk.io/v1",
} as const;

export type ChkkEnvironment = typeof ChkkEnvironment.Production | typeof ChkkEnvironment.ProductionAwsUsWest2;
