/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface CreateIntegrationRequestBody {
    /** ??? */
    integrationName: string;
    integrationType: Chkk.IntegrationType;
    status: Chkk.IntegrationStatus;
    slackConfiguration?: Chkk.IntegrationSlackConfiguration;
    jiraConfiguration?: Chkk.IntegrationJiraConfiguration;
}
