/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * ???
 */
export interface IntegrationJiraConfiguration {
    /** ??? */
    jiraUser: string;
    /** ??? */
    jiraToken: string;
    /** ??? */
    jiraUrl: string;
    /** ??? */
    jiraProjectKey: string;
}
