/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface IntegrationSlackAppConfiguration {
    team?: Chkk.IntegrationSlackAppConfigurationTeam;
    enterprise?: Chkk.IntegrationSlackAppConfigurationEnterprise;
    user: Chkk.IntegrationSlackAppConfigurationUser;
    /** Whether the installation was performed on an enterprise org. Synthesized as `false` when not present */
    isEnterpriseInstall?: boolean;
    /** When the installation is an enterprise org install, the URL of the landing page for all workspaces in the org. */
    enterpriseUrl?: string;
    bot?: Chkk.IntegrationSlackAppConfigurationBot;
}
