/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface IntegrationSlackAppConfigurationBot {
    token: string;
    refreshToken?: string;
    expiresAt?: number;
    id: string;
    userId: string;
}
