/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { Chkk } from "@fern-api/chkk";

/**
 * ???
 */
export interface ListIntegrationsResponse {
    /** ??? */
    data: Chkk.Integration[];
    /** ??? */
    hasMore: boolean;
}
