/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ChkkAgent: core.serialization.ObjectSchema<serializers.ChkkAgent.Raw, Chkk.ChkkAgent> =
    core.serialization.object({
        version: core.serialization.string(),
        gitCommit: core.serialization.property("git_commit", core.serialization.string()),
        buildDate: core.serialization.property("build_date", core.serialization.string()),
        config: core.serialization.record(
            core.serialization.string(),
            core.serialization.lazy(async () => (await import("../../..")).InlineTypeString).optional()
        ),
        namespace: core.serialization.string(),
    });

export declare namespace ChkkAgent {
    interface Raw {
        version: string;
        git_commit: string;
        build_date: string;
        config: Record<string, serializers.InlineTypeString.Raw | null | undefined>;
        namespace: string;
    }
}
