/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ClusterDetectedLarMitigation: core.serialization.ObjectSchema<
    serializers.ClusterDetectedLarMitigation.Raw,
    Chkk.ClusterDetectedLarMitigation
> = core.serialization.object({
    description: core.serialization.string(),
});

export declare namespace ClusterDetectedLarMitigation {
    interface Raw {
        description: string;
    }
}
