/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ClusterDetectedLar: core.serialization.ObjectSchema<
    serializers.ClusterDetectedLar.Raw,
    Chkk.ClusterDetectedLar
> = core.serialization.object({
    signatureId: core.serialization.property("signature_id", core.serialization.string()),
    severity: core.serialization.string(),
    availabilityImpact: core.serialization.property("availability_impact", core.serialization.string()),
    title: core.serialization.string(),
    url: core.serialization.string(),
    needAttention: core.serialization.property("need_attention", core.serialization.boolean()),
    labels: core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).SignatureLabel)),
    remediations: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ClusterDetectedLarRemidiation)
    ),
    triggerConditions: core.serialization.property(
        "trigger_conditions",
        core.serialization.lazyObject(async () => (await import("../../..")).ClusterDetectedLarTriggerConditions)
    ),
    mitigations: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ClusterDetectedLarMitigation)
    ),
    resources: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../..")).ClusterDetectedLarAffectedResource)
    ),
});

export declare namespace ClusterDetectedLar {
    interface Raw {
        signature_id: string;
        severity: string;
        availability_impact: string;
        title: string;
        url: string;
        need_attention: boolean;
        labels: serializers.SignatureLabel.Raw[];
        remediations: serializers.ClusterDetectedLarRemidiation.Raw[];
        trigger_conditions: serializers.ClusterDetectedLarTriggerConditions.Raw;
        mitigations: serializers.ClusterDetectedLarMitigation.Raw[];
        resources: serializers.ClusterDetectedLarAffectedResource.Raw[];
    }
}
