/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ClusterDetectedLarAffectedResource: core.serialization.ObjectSchema<
    serializers.ClusterDetectedLarAffectedResource.Raw,
    Chkk.ClusterDetectedLarAffectedResource
> = core.serialization.object({
    kind: core.serialization.string(),
    name: core.serialization.string(),
    namespace: core.serialization.string(),
});

export declare namespace ClusterDetectedLarAffectedResource {
    interface Raw {
        kind: string;
        name: string;
        namespace: string;
    }
}
