/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const KubernetesProvider: core.serialization.Schema<
    serializers.KubernetesProvider.Raw,
    Chkk.KubernetesProvider
> = core.serialization.enum_(["EKS", "KinD", "GKE", "AKS", "Minikube", "local"]);

export declare namespace KubernetesProvider {
    type Raw = "EKS" | "KinD" | "GKE" | "AKS" | "Minikube" | "local";
}
