/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const ListClusterScansResponse: core.serialization.ObjectSchema<
    serializers.ListClusterScansResponse.Raw,
    Chkk.ListClusterScansResponse
> = core.serialization.object({
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    data: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).ClusterScan)),
});

export declare namespace ListClusterScansResponse {
    interface Raw {
        has_more: boolean;
        data: serializers.ClusterScan.Raw[];
    }
}
