/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const Severity: core.serialization.Schema<serializers.Severity.Raw, Chkk.Severity> = core.serialization.enum_([
    "Critical",
    "High",
    "Medium",
    "Low",
]);

export declare namespace Severity {
    type Raw = "Critical" | "High" | "Medium" | "Low";
}
