/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Chkk } from "@fern-api/chkk";
import * as core from "../../../../core";

export const SignatureLabel: core.serialization.Schema<serializers.SignatureLabel.Raw, Chkk.SignatureLabel> =
    core.serialization.record(
        core.serialization.string(),
        core.serialization.lazy(async () => (await import("../../..")).StringProperty).optional()
    );

export declare namespace SignatureLabel {
    type Raw = Record<string, serializers.StringProperty.Raw | null | undefined>;
}
